<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250507035616 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE category (code VARCHAR(2) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(code))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE rank (code VARCHAR(2) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(code))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE school (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, city VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE sportsman (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, passport_number VARCHAR(255) DEFAULT NULL, gender VARCHAR(6) DEFAULT 'male', birthdate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, school_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, category_code VARCHAR(2) DEFAULT NULL, rank_code VARCHAR(2) DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_sportsman_category_code ON sportsman (category_code)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_sportsman_rank_code ON sportsman (rank_code)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_sportsman_school_id ON sportsman (school_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX udx_sportsman_user_id ON sportsman (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, login VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, hashed_password VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sportsman ADD CONSTRAINT fk_sportsman_category_code FOREIGN KEY (category_code) REFERENCES category (code) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sportsman ADD CONSTRAINT fk_sportsman_rank_code FOREIGN KEY (rank_code) REFERENCES rank (code) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sportsman ADD CONSTRAINT fk_sportsman_school_id FOREIGN KEY (school_id) REFERENCES school (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sportsman ADD CONSTRAINT fk_sportsman_user_id FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO rank (code, title) VALUES
                ('1Y', 'Первый юношеский'),
                ('2Y', 'Второй юношеский'),
                ('3Y', 'Третий юношеский'),
                ('1R', 'Первый разряд'),
                ('2R', 'Второй разряд'),
                ('3R', 'Третий разряд'),
                ('MS',  'Мастер спорта'),
                ('MM',  'Мастер спорта международного класса');
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE sportsman DROP CONSTRAINT fk_sportsman_user_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sportsman DROP CONSTRAINT fk_sportsman_school_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sportsman DROP CONSTRAINT fk_sportsman_rank_code
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sportsman DROP CONSTRAINT fk_sportsman_category_code
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE category
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE rank
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE school
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE sportsman
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE users
        SQL);
    }
}
